deleting all tasks
Floride125-art/Tasks pull request #9
Opened 2020-11-11 13:40 UTC by Sandrine21

2020-11-11 15:46 UTC, Sandrine21 commented
User will be able to delete all task.

2020-11-11 20:21 UTC, mujohn26 requested changes

2020-11-11 20:21 UTC, mujohn26 commented on lib/View-tasks.Dart
> +                    // textAlign: TextAlign.center,
@Sandrine21 Please remove these comments

2020-11-11 20:22 UTC, mujohn26 commented
> _No description provided._

@Sandrine21 Please I need descriptions of this PR, I really don't know what you worked on.

2020-11-12 12:36 UTC, mujohn26 approved these changes
Good !

2020-11-12 12:36 UTC, merged